//Array of all sites to be scraped

Meteor.scrapes = [
	{
		'sitename': 'Y Combinator',
		'url': 'https://news.ycombinator.com/jobs',
		'container': 'td.title:last-child',
		'titles': 'a',
		'engagements': '',
		'locations': '',
		'companies': '.comhead',
		'links': 'a',
		'linkprefix': 'https://news.ycombinator.com/',
		'pageindex': '',
		'maxpage': '',
		'icon': 'ycombinator'
	},
	{
		'sitename': 'Smashing Magazine',
		'url': 'http://jobs.smashingmagazine.com/all/programming',
		'container': '.entry-list li',
		'titles': 'article.entry h2',
		'engagements': 'article.entry .entry-type',
		'locations': '',
		'companies': ' article.entry .entry-company',
		'links': 'a',
		'linkprefix': '',
		'pageindex': '',
		'maxpage': '',
		'icon': 'smashing-magazine'
	},
	{
		'sitename': 'Stack Overflow',
		'url': 'http://careers.stackoverflow.com/jobs',
		'container': '.-job',
		'titles': 'a.job-link',
		'engagements': '',
		'locations': '.location',
		'companies': '',
		'links': 'a.job-link',
		'linkprefix': 'http://careers.stackoverflow.com',
		'pageindex': '?pg=',
		'maxpage': '15',
		'icon': 'stackoverflow'
	},
	{
		'sitename': 'GitHub',
		'url': 'https://jobs.github.com/positions',
		'container': '.positionlist tr:not(.pagination)',
		'titles': '.title a',
		'engagements': 'p.source strong',
		'locations': 'span.location',
		'companies': '.company',
		'links': '.title a',
		'linkprefix': 'https://jobs.github.com',
		'pageindex': '?page=',
		'maxpage': '4',
		'startpage': '0',
		'icon': 'github'
	},
	{
		'sitename': 'JavaScript Ninja',
		'url': 'http://jobs.jsninja.com/a/jbb/find-jobs',
		'container': 'tr.listing-meta',
		'titles': '.title a',
		'engagements': '',
		'locations': 'td.location',
		'companies': 'td.company',
		'links': '.title a',
		'linkprefix': 'http://jobs.jsninja.com',
		'pageindex': '',
		'maxpage': '',
		'icon': 'jsninja'
	},
	{
		'sitename': 'Top Ruby Jobs',
		'url': 'https://toprubyjobs.com/',
		'container': 'li.job',
		'titles': 'h4.job-title a',
		'engagements': 'p.job-type',
		'locations': '',
		'companies': 'p.job-info',
		'links': 'h4.job-title a',
		'linkprefix': 'https://toprubyjobs.com',
		'pageindex': '',
		'maxpage': '',
		'icon': 'toprubyjobs'
	},
	{
		'sitename': 'Ruby Now',
		'url': 'http://jobs.rubynow.com/',
		'container': 'ul.jobs li',
		'titles': 'h3 a',
		'engagements': 'p.job-type',
		'locations': '',
		'companies': 'h3 span',
		'links': 'h3 a',
		'linkprefix': 'http://jobs.rubynow.com',
		'pageindex': '',
		'maxpage': '',
		'icon': 'rubynow'
	},
	{
		'sitename': 'Ruby Inside',
		'url': 'http://jobs.rubyinside.com/a/jbb/find-jobs',
		'container': 'tr.listing-meta',
		'titles': '.title a',
		'engagements': '',
		'locations': 'td.location',
		'companies': 'td.company',
		'links': '.title a',
		'linkprefix': 'http://jobs.rubyinside.com',
		'pageindex': '',
		'maxpage': '',
		'icon': 'rubyinside'
	},
	{
		'sitename': 'We Work Remotely',
		'url': 'https://weworkremotely.com/categories/2/jobs',
		'container': 'li:not(:last-child)',
		'titles': 'span.title',
		'engagements': '',
		'locations': '',
		'companies': 'span.company',
		'links': 'a',
		'linkprefix': 'https://weworkremotely.com',
		'pageindex': '',
		'maxpage': '',
		'icon': 'weworkremotely'
	},
	{
		'sitename': 'Node Jobs',
		'url': 'http://www.nodejobs.com/',
		'container': 'li.item',
		'titles': 'big a',
		'engagements': '',
		'locations': '',
		'companies': 'small a',
		'links': 'big a',
		'linkprefix': 'http://www.nodejobs.com',
		'pageindex': '',
		'maxpage': '',
		'icon': 'nodejobs'
	},
	{
		'sitename': 'JSJobs',
		'url': 'http://jsjobs.org/',
		'container': 'div.job',
		'titles': 'h6 a',
		'engagements': '',
		'locations': 'p br',
		'companies': 'p em',
		'links': 'h6 a',
		'linkprefix': 'http://jsjobs.org',
		'pageindex': '?p=',
		'maxpage': '12',
		'icon': 'jsjobs'
	},
	{
		'sitename': 'Python Jobs',
		'url': 'http://www.pythonjobs.com/',
		'container': 'div.job',
		'titles': 'div.title a',
		'engagements': '',
		'locations': 'div.location',
		'companies': 'div.company',
		'links': 'div.title a',
		'linkprefix': 'http://www.pythonjobs.com',
		'pageindex': '?pg=',
		'maxpage': '5',
		'icon': 'pythonjobs'
	},
	{
		'sitename': 'PHP Jobs',
		'url': 'http://www.phpjobs.com/',
		'container': 'table tr.alternate2:not(:last-child),table tr.alternate1:not(:last-child)',
		'titles': '.jobs-list-title a',
		'engagements': '',
		'locations': 'span.location',
		'companies': 'span.company-name',
		'links': '.jobs-list-title a',
		'linkprefix': '',
		'pageindex': '',
		'maxpage': '',
		'icon': 'phpjobs'
	},
	{
		'sitename': 'JOBBOX',
		'url': 'http://www.jobbox.io/offers',
		'container': 'li.row div.job',
		'titles': 'a .job_title',
		'engagements': '',
		'locations': 'a .location',
		'companies': 'a .company_name',
		'links': 'a',
		'linkprefix': 'http://www.jobbox.io',
		'pageindex': '?page=',
		'maxpage': '2',
		'icon': 'jobbox'
	},
	{
		'sitename': 'Ars Technica',
		'url': 'http://jobs.thejobnetwork.com/RMAPI/widgets/Widget.svc/GetFeaturedJobs?header={%22TokenId%22:0,%22AffiliateId%22:%222432%22,%22SessionId%22:null}&body={%22affiliateId%22:%222432%22,%22WidgetId%22:%221753%22,%22LocationIds%22:[],%22Count%22:50}',
		'container': 'Jobs',
		'titles': 'Title',
		'engagements': '',
		'locations': 'Location',
		'companies': 'CompanyName',
		'links': 'JobUrl',
		'linkprefix': '',
		'pageindex': '',
		'maxpage': '',
		'icon': '',
		'json': 'true'
	},
	{
		'sitename': 'Perl.com',
		'url': 'http://jobs.perl.com/a/jbb/find-jobs',
		'container': '.listing-meta',
		'titles': 'td.title',
		'engagements': '',
		'locations': 'td.location',
		'companies': 'td.company',
		'links': 'a.jam_link',
		'linkprefix': '',
		'pageindex': '',
		'maxpage': '',
		'icon': ''
	},
	{
		'sitename': 'ProductHunt',
		'url': 'http://www.producthunt.com/jobs',
		'container': 'li.job',
		'titles': 'span.description',
		'engagements': '',
		'locations': '',
		'companies': 'span.company',
		'links': 'a.title',
		'linkprefix': '',
		'pageindex': '',
		'maxpage': '',
		'icon': 'producthunt',
		'removestring': 'is hiring a'
	},
	{
		'sitename': 'GapJumpers',
		'url': 'https://www.gapjumpers.me/questions/?category=TCH&position_type=JB',
		'container': 'div.offers-Mod2',
		'titles': 'a.question-listing',
		'engagements': '',
		'locations': 'span.local-offers',
		'companies': 'span.jobEnterprise',
		'links': 'a.question-listing',
		'linkprefix': 'https://www.gapjumpers.me',
		'pageindex': '',
		'maxpage': '',
		'icon': 'gapjumpers'
	},
	{
		'sitename': 'CodePen',
		'url': 'http://codepen.io/jobs',
		'container': 'div.job',
		'titles': 'h3.job-title',
		'engagements': '',
		'locations': 'div.job-location',
		'companies': 'span.job-company',
		'links': 'a',
		'linkprefix': 'http://codepen.io',
		'pageindex': '',
		'maxpage': '',
		'icon': 'codepen'
	}
];
